### ISSUE TITLE
"Show address" doesn't show last character on a Nano S

### ISSUE THREAD

**Issue by veox** [LedgerHQ/blue-app-eth#6] opened 2017-09-28 12:10 UTC
When using MEW and clicking the link/button to show the address on the device, the last nibble is not displayed.

So, for example, if my address was

`0x04b3fAAA7c8127A80eB6D24672CfdAF4AeCABbF8`

the device scroll-shows

`0x04b3faaa7c8127a80eb6d24672cfdaf4aecabbf`

**Comment by btchip** [comment] 2017-09-28 12:12
yes, the problem is well known. Will be fixed soon.

**Comment by btchip** [comment] 2017-12-25 18:47
Fixed in 1.0.21

**Closed by btchip** 2017-12-25 18:47 UTC
